/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val mensaje: String = "Mi edad es: "
    var numero = 16
    println("$mensaje $numero")
    println(App().greeting)
}
